cargo-features = ["profile-rustflags"]
[package]
name = "stage2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "*"
log = "0.4"
csv = "1.1.6"
thiserror = "1.0"
num = "0.4.0"
nom = "7.1.1"
superslice = "1"
macros = { path = "libs/macros" }

[dev-dependencies]
env_logger = "*"
test-log = "0.2"
criterion = {version = "0.3", features = [ "html_reports" ] }
rand = "0.8"
rand_pcg = "0.3"
quickcheck = "1"
quickcheck_macros = "1"
arbitrary = { version = "1", features = ["derive"] }

[target.'cfg(unix)'.dev-dependencies]
iai = "0.1" # needs valgrind -> unix only

[profile.dev]
panic = "unwind"

[profile.release]
panic = "abort"

[profile.release-lto]
inherits = "release"
lto = "fat"

[profile.release-lto-opt2]
inherits = "release-lto"
opt-level = 2

[profile.releaserf]
inherits = "release"
rustflags = [ "-C", "target-cpu=native" ]

[profile.release-ltorf]
inherits = "release-lto"
rustflags = [ "-C", "target-cpu=native" ]

[profile.release-lto-opt2rf]
inherits = "release-lto-opt2"
rustflags = [ "-C", "target-cpu=native" ]

[profile.release_cg]
inherits = "release"
codegen-units = 1

[profile.release-lto_cg]
inherits = "release"
lto = "fat"
codegen-units = 1

[profile.release-lto-opt2_cg]
inherits = "release-lto"
opt-level = 2
codgen-units = 1

[profile.releaserf_cg]
inherits = "release_cg"
rustflags = [ "-C", "target-cpu=native" ]

[profile.release-ltorf_cg]
inherits = "release-lto_cg"
rustflags = [ "-C", "target-cpu=native" ]

[profile.release-lto-opt2rf_cg]
inherits = "release-lto-opt2_cg"
rustflags = [ "-C", "target-cpu=native" ]



[[bench]]
name = "seek"
harness = false

# iai - based benchmarks, only on unix
[[bench]]
name = "seek_iai"
harness = false
